# Generated by Django 2.2.7 on 2019-12-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of your game.', max_length=600, unique=True)),
                ('price', models.CharField(help_text='The price of your game.', max_length=50)),
                ('image_url', models.CharField(help_text='The URL of an image of your game.', max_length=1000)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this game. Generated by the system.', max_length=600)),
                ('description', models.TextField(help_text="Write your game's description here.")),
            ],
        ),
    ]
