# Generated by Django 2.2.7 on 2019-12-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='author',
        ),
    ]
